/* Run with PLAYWRIGHT_MODULE pointing to an installed playwright package. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('child_process');const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const data=path.join(out,'browser-'+Date.now());const port=8766,url=`http://127.0.0.1:${port}`;
const python=process.env.TEST_PYTHON||path.resolve(root,'../.venv/Scripts/python.exe');
const log=fs.openSync(path.join(out,'browser-server.log'),'w');
const server=spawn(python,[path.join(root,'run.py')],{cwd:root,windowsHide:true,env:{...process.env,COURSE_DATA_DIR:data,APP_PORT:String(port),APP_ORIGIN:url,BOOTSTRAP_PASSWORD:'Browser-Test-Only-24680'},stdio:['ignore',log,log]});
let browser;
async function main(){for(let i=0;i<80;i++){try{if((await fetch(url+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,150))}
browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
async function go(hash){await page.goto(url+'/#'+hash);await page.locator('#content h1').first().waitFor();await page.locator('.loading').waitFor({state:'detached'});}
async function click(a){if(a==='logout'&&!(await page.locator('[data-action=logout]').isVisible()))await page.locator('.account-menu summary').click();await page.locator(`[data-action="${a}"]`).first().click()}
async function login(email,password){await click('login');await page.locator('#auth-form [name=email]').fill(email);await page.locator('#auth-form [name=password]').fill(password);await page.locator('#auth-form button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});await page.locator('.account-menu summary').waitFor();}
await go('catalog');assert.equal(await page.locator('.course').count(),47);await page.screenshot({path:path.join(out,'catalog-desktop.png')});
for(const width of [320,390,768,1024]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(out,`catalog-${width}.png`)});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Overflow ${width}`)}
await page.setViewportSize({width:1440,height:1050});await login('owner@local.test','Browser-Test-Only-24680');
assert.equal(await page.locator('.nav-group').count(),4);
await page.locator('.nav-group').filter({hasText:'培训方案'}).locator('summary').click();await page.getByRole('link',{name:'智能组课',exact:true}).click();await page.locator('#agent-form').waitFor();
await go('workspace');await page.getByRole('heading',{name:'机构工作台',exact:true}).waitFor();await page.screenshot({path:path.join(out,'workspace.png')});
await go('members');await page.locator('[data-org-action=invite]').click();await page.locator('#orgx-invite [name=role]').selectOption('teacher');await page.locator('#orgx-invite [name=email]').fill('teacher-ui@example.test');await page.locator('#orgx-invite button[type=submit]').click();await page.locator('#invite-result a').waitFor();const invite=await page.locator('#invite-result a').getAttribute('href');assert(invite.includes('invite='));await click('close');
await go('edit');const form=page.locator('#module-form');for(const [name,value]of Object.entries({title:'浏览器验收：口播实操',intro:'用一个短镜头学习口播制作。',description:'针对社会学员，从文案、镜头到剪辑完成可检查的视频成果。',objectives:'掌握口播制作流程\n完成短片并自检',exercise:'制作一段15秒口播',output:'15秒口播视频',criteria:'文案完整\n声音和画面同步',price:'120'}))await form.locator(`[name=${name}]`).fill(value);
await form.locator('button[type=submit]').click();await page.locator('[data-action=review-submit]').waitFor();const mid=new URLSearchParams(page.url().split('?')[1]).get('id');assert(mid);
await page.locator('#upload-form [name=file]').setInputFiles({name:'公开教案.txt',mimeType:'text/plain',buffer:Buffer.from('课堂练习资料')});await page.locator('#upload-form [name=visibility]').selectOption('public');await page.locator('#upload-form button[type=submit]').click();await page.getByRole('link',{name:'公开教案.txt',exact:true}).waitFor();
const videoBytes=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=90;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(12),recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(r=>recorder.onstop=r);let n=0;const timer=setInterval(()=>{ctx.fillStyle=n++%2?'#123f37':'#d8b971';ctx.fillRect(0,0,160,90)},80);recorder.start();await new Promise(r=>setTimeout(r,1200));recorder.stop();await stopped;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())]});
for(const file of [{name:'课程课件.pptx',mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',buffer:Buffer.from('PK-test-presentation')},{name:'课件预览.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 0/Kids[]>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF')},{name:'课程录播.webm',mimeType:'video/webm',buffer:Buffer.from(videoBytes)}]){await page.locator('#upload-form [name=file]').setInputFiles(file);await page.locator('#upload-form [name=visibility]').selectOption('public');await page.locator('#upload-form button[type=submit]').click();await page.getByRole('link',{name:file.name,exact:true}).waitFor()}
await click('review-submit');await page.locator('[data-action=review-approve]').waitFor();await click('review-approve');await page.getByRole('button',{name:'保存为新版本草稿',exact:true}).waitFor();
await go('catalog');await page.locator(`[data-action=detail][data-id="${mid}"]`).click();await page.locator('.course-detail').waitFor();assert.equal(await page.locator('.course-dialog .doc,.course-dialog .module-doc').count(),0);await page.screenshot({path:path.join(out,'course-detail-overview.png')});
await page.getByRole('tab',{name:'教学大纲',exact:true}).click();assert.equal(await page.locator('.syllabus-timeline>li').count(),3);await page.screenshot({path:path.join(out,'course-detail-syllabus.png')});
await page.getByRole('tab',{name:'课程资料',exact:true}).click();await page.screenshot({path:path.join(out,'course-detail-resources.png')});
const videoRow=page.locator('.resource-entry').filter({hasText:'课程录播.webm'});await videoRow.getByRole('button',{name:'播放视频'}).click();await page.locator('video').evaluate(async v=>{await v.play();await new Promise(resolve=>v.addEventListener('ended',resolve,{once:true}))});
await click('close-preview');await page.locator('.resource-entry').filter({hasText:'课件预览.pdf'}).getByRole('button',{name:'在线预览'}).click();assert.equal(await page.locator('#resource-viewer iframe').count(),1);
const pptEvent=page.waitForEvent('download');await page.locator('.resource-entry').filter({hasText:'课程课件.pptx'}).getByRole('link',{name:'下载',exact:true}).click();assert.equal((await pptEvent).suggestedFilename(),'课程课件.pptx');await click('close-preview');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'course-detail-mobile.png')});assert(await page.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await click('close');
await page.locator('.nav-group > summary').filter({hasText:'机构管理'}).click();await page.getByRole('link',{name:'课程管理',exact:true}).click();await page.getByRole('heading',{name:'课程管理',exact:true}).waitFor();assert.equal(await page.locator('.nav-group[open]').count(),0);await page.setViewportSize({width:1440,height:1050});await go('catalog');
await click('logout');await click('login');await click('register');await page.locator('#auth-form [name=email]').fill('customer-ui@example.test');await page.locator('#auth-form [name=name]').fill('验收客户');await page.locator('#auth-form [name=password]').fill('Customer-UI-Only-24680');await page.locator('#auth-form button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});
await page.locator(`[data-action=cart][data-id="${mid}"]`).click();await go('plan');await page.locator('#plan-output .doc').waitFor();await page.locator('#plan-form [name=days]').fill('1');await page.locator('#plan-form [name=batches]').fill('2');await click('save-plan');await page.getByRole('status').filter({hasText:'方案已保存'}).waitFor();
await click('inquire');await page.locator('#inquiry-form [name=phone]').fill('test-contact');await page.locator('#inquiry-form button[type=submit]').click();await page.getByRole('heading',{name:'项目报价',exact:true}).waitFor();const iid=new URLSearchParams(page.url().split('?')[1]).get('id');assert(iid);
await go('agent');await page.locator('#agent-form button[type=submit]').click();await page.locator('[data-action=apply-agent]').waitFor();assert((await page.locator('#agent-result').textContent()).includes('规则组课结果'));await page.screenshot({path:path.join(out,'agent.png')});await click('apply-agent');await page.locator('#plan-output .doc').waitFor();
await click('logout');await login('owner@local.test','Browser-Test-Only-24680');await go('inquiry?id='+iid);await click('quote-new');await page.locator('#quote-form [name=extras]').fill('授课服务 | 800');await page.locator('#quote-form button[type=submit]').click();await page.locator('[data-action=quote-send]').waitFor();await click('quote-send');await page.locator('.quote-doc').filter({hasText:'待客户确认'}).waitFor();await page.screenshot({path:path.join(out,'quote.png')});
await click('logout');await login('customer-ui@example.test','Customer-UI-Only-24680');await go('inquiry?id='+iid);await click('quote-accept');await page.getByRole('heading',{name:'已确认',exact:true}).waitFor();
await go('saved');await page.locator('[data-action=load-plan]').first().click();await page.locator('#plan-output .doc').waitFor();assert((await page.locator('#plan-output').textContent()).includes('浏览器验收'));
await page.locator('#plan-form [name=introduction]').fill('这是经编辑确认的方案简介。');await click('save-plan');await page.getByRole('status').filter({hasText:'方案已保存'}).waitFor();
const downloadEvent=page.waitForEvent('download');await click('export-json');const downloaded=await downloadEvent;const jsonFile=await downloaded.path();await click('import');await page.locator('#import-form [name=file]').setInputFiles(jsonFile);await page.locator('#import-form button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#plan-form [name=introduction]').inputValue(),'这是经编辑确认的方案简介。');
await click('import');await page.locator('#import-form [name=file]').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schema:'aigc-course-plan/v2',state:{ids:['F01','T01','P02','F12'],audience:'social',daily:6,target:1,title:'旧版导入验证',notes:'旧版组合',equivalent:false}}))});await page.locator('#import-form button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#plan-form [name=title]').inputValue(),'旧版导入验证');
await go('paths');await page.locator('[data-action=path-node]').first().click();await page.getByRole('heading',{name:'先修条件 · 全部满足',exact:true}).waitFor();await click('close');await page.locator('[data-action=preset]').first().click();await page.locator('#plan-output .doc').waitFor();assert((await page.locator('#plan-form [name=title]').inputValue()).includes('1天'));
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({ok:true,checks:['47-module catalog','320/390/768/1024 responsive widths','owner login','workspace','invitation link','module authoring','resource upload','review and publish','customer registration','cart and saved plan','inquiry snapshot','rule agent','quote send','customer confirmation','saved plan reload'],consoleErrors:errors},null,2));console.log('Browser acceptance passed. Screenshots and report: '+out);
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill();fs.closeSync(log)});
