/* Isolated browser acceptance: organization hierarchy and ordinary-user lifecycle. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('child_process');const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results'),data=path.join(out,'organizations-'+Date.now());fs.mkdirSync(data,{recursive:true});
const url='http://127.0.0.1:8767',python=process.env.TEST_PYTHON||path.resolve(root,'../.venv/Scripts/python.exe');
const log=fs.openSync(path.join(data,'server.log'),'w');
const server=spawn(python,[path.join(root,'run.py')],{cwd:root,windowsHide:true,env:{...process.env,COURSE_DATA_DIR:data,APP_PORT:'8767',APP_ORIGIN:url,BOOTSTRAP_PASSWORD:'Org-Browser-Test-24680'},stdio:['ignore',log,log]});let browser,page;
async function main(){
 for(let i=0;i<60;i++){try{if((await fetch(url+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,200))}
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 async function go(hash){await page.goto(url+'/#'+hash);await page.locator('#content h1').first().waitFor();await page.locator('.loading').waitFor({state:'detached'})}
 async function act(a){await page.locator(`[data-org-action="${a}"]`).first().click()}
 async function save(id){await page.locator('#'+id+' button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'})}
 async function login(email,password){await page.locator('[data-action=login]').first().click();await page.locator('#auth-form [name=email]').fill(email);await page.locator('#auth-form [name=password]').fill(password);await save('auth-form')}
 await go('catalog');assert.equal(await page.locator('.topbar #training-theme-select option:checked').textContent(),'AIGC视频创作学院');assert.equal(await page.locator('.sidebar #org-select option:checked').textContent(),'微墨AIGC培训学院');await login('owner@local.test','Org-Browser-Test-24680');await go('departments');await act('department-add');await page.locator('#orgx-department [name=name]').fill('数字创作中心');await save('orgx-department');await page.locator('.department-row').filter({hasText:'数字创作中心'}).waitFor();
 await act('department-child');await page.locator('#orgx-department [name=name]').fill('短剧制作组');await save('orgx-department');await page.locator('.department-row').filter({hasText:'短剧制作组'}).waitFor();await page.screenshot({path:path.join(out,'organizations-tree.png')});
 await go('platform-users');await act('user-add');await page.locator('#orgx-user [name=name]').fill('组织验收学员');await page.locator('#orgx-user [name=email]').fill('org-student@example.test');await page.locator('#orgx-user button[type=submit]').click();await page.locator('.initial-password').waitFor();const password=await page.locator('.initial-password').textContent();assert(password.length>=18);
 await page.locator('#dialog [data-org-action=user-memberships]').click();await act('membership-add');await page.locator('#membership-department').selectOption({label:'　短剧制作组'});await page.locator('#orgx-membership [name=job_title]').fill('研修学员');await save('orgx-membership');await page.locator('.directory-table tr').filter({hasText:'org-student@example.test'}).filter({hasText:'短剧制作组'}).waitFor();
 await go('members');await page.locator('[data-org-action=department-filter]').filter({hasText:'数字创作中心'}).click();await page.locator('.directory-table tr').filter({hasText:'组织验收学员'}).waitFor();assert.equal(await page.locator('.directory-table tbody tr').count(),1);
 await act('member-edit');await page.locator('#orgx-member [name=department_id]').selectOption({label:'数字创作中心'});await save('orgx-member');await page.locator('.directory-table tr').filter({hasText:'组织验收学员'}).filter({hasText:'数字创作中心'}).waitFor();
 await act('invite');await page.locator('#orgx-invite [name=email]').fill('pending-student@example.test');await page.locator('#orgx-invite [name=department_id]').selectOption({label:'　短剧制作组'});await page.locator('#orgx-invite button[type=submit]').click();await page.locator('#invite-result a').waitFor();await page.locator('[data-action=close]').click();await go('members');await page.locator('.org-invitations summary').click();await act('invite-revoke');await page.locator('.org-invitations summary').click();await page.locator('.org-invitations').filter({hasText:'已撤销'}).waitFor();
 await go('platform-orgs');await act('platform-org-add');await page.locator('#orgx-platform-org [name=name]').fill('组织验收分校');await page.locator('#orgx-platform-org [name=owner_email]').fill('org-student@example.test');await save('orgx-platform-org');await page.locator('.org-cards article').filter({hasText:'组织验收分校'}).waitFor();await page.screenshot({path:path.join(out,'organizations-platform.png')});const firstOrg=await page.locator('#org-select').inputValue();await page.locator('#org-select').selectOption({label:'组织验收分校'});await page.locator('#content h1').filter({hasText:'AI视频创作'}).waitFor();assert.equal(await page.locator('#training-theme-select').inputValue(),'aigc-video');assert.equal(await page.locator('.course').count(),0);await page.locator('#org-select').selectOption(firstOrg);await page.locator('.course').first().waitFor();assert.equal(await page.locator('#training-theme-select option:checked').textContent(),'AIGC视频创作学院');
 for(const hash of ['members','departments','platform-users','platform-orgs']){await go(hash);for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Overflow ${hash} ${width}`)} }
 await go('members');await page.screenshot({path:path.join(out,'organizations-members.png')});await page.setViewportSize({width:390,height:900});await page.screenshot({path:path.join(out,'organizations-mobile.png')});
 await page.locator('.account-menu summary').click();await page.locator('[data-action=logout]').click();await login('org-student@example.test',password);await go('my-organizations');await page.locator('.org-cards').filter({hasText:'数字创作中心'}).waitFor();assert.equal(await page.locator('.org-cards article').count(),2);
 // In the first institution the ordinary member sees no management navigation.
 await page.locator('[data-org-action=switch-org]').first().click();await page.locator('.course').first().waitFor();assert.equal(await page.locator('.nav-group').count(),2);
 await go('settings');await page.getByRole('heading',{name:'修改密码',exact:true}).waitFor();assert.equal(await page.locator('#org-form').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'organizations-report.json'),JSON.stringify({ok:true,checks:['department hierarchy','account creation','multi-organization membership','member transfer','invite revoke','ordinary member navigation','mobile layout','ordinary member settings'],errors},null,2));console.log('Organization browser acceptance passed');
}
main().catch(async e=>{if(page){await page.screenshot({path:path.join(out,'organizations-failure.png')});fs.writeFileSync(path.join(out,'organizations-failure.html'),await page.content())}console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill();fs.closeSync(log)});
