/* Browser integration acceptance, with simulated external providers only. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('child_process'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results'),data=path.join(out,'studio-'+Date.now());fs.mkdirSync(data,{recursive:true});
const url='http://127.0.0.1:8768',python=path.resolve(root,'../.venv/Scripts/python.exe'),log=fs.openSync(path.join(data,'server.log'),'w');
const server=spawn(python,[path.join(root,'tests/studio_server.py')],{cwd:root,windowsHide:true,env:{...process.env,COURSE_DATA_DIR:data,APP_ORIGIN:url,BOOTSTRAP_PASSWORD:'Studio-Test-24680',SILICONFLOW_API_KEY:'fixture-not-real'},stdio:['ignore',log,log]});let browser,page;
(async()=>{
 for(let i=0;i<60;i++){try{if((await fetch(url+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,200))}
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('.course').first().waitFor();await page.locator('[data-action=login]').click();await page.locator('#auth-form [name=email]').fill('owner@local.test');await page.locator('#auth-form [name=password]').fill('Studio-Test-24680');await page.locator('#auth-form button[type=submit]').click();await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('[data-action=cart]').first().click();await page.goto(url+'/#plan');await page.locator('#plan-output .doc').waitFor();
 await page.locator('[data-action=studio-copy]').click();await page.locator('[data-action=studio-apply]').waitFor({timeout:30000});await page.locator('[name=studio-field][value=title]').uncheck();await page.locator('[data-action=studio-apply]').click();await page.locator('#plan-form [name=objectives]').waitFor();assert((await page.locator('#plan-form [name=objectives]').inputValue()).includes('说明视频制作流程'));assert.equal(await page.locator('#plan-form [name=title]').inputValue(),'');
 await page.locator('[name=title]').fill('验收课程方案');await page.locator('[data-action=save-plan]').click();await page.getByText('方案已保存',{exact:true}).waitFor();await page.reload();await page.goto(url+'/#saved');await page.locator('[data-action=load-plan]').first().click();await page.locator('#plan-form [name=objectives]').waitFor();assert((await page.locator('#plan-form [name=objectives]').inputValue()).includes('说明视频制作流程'));
 await page.locator('[data-action=studio-poster]').click();await page.locator('#poster-canvas').waitFor();await page.locator('[name=poster-style]').selectOption('creative');await page.locator('[name=poster-title]').fill('短视频创作公开课');await page.screenshot({path:path.join(out,'studio-poster.png')});
 const download=page.waitForEvent('download');await page.locator('[data-action=studio-download]').click();const file=await download;await file.saveAs(path.join(out,'studio-poster-export.png'));const png=fs.readFileSync(path.join(out,'studio-poster-export.png'));assert.equal(png.readUInt32BE(16),1080);assert.equal(png.readUInt32BE(20),1440);
 await page.locator('[data-action=studio-image]').click();await page.locator('[data-action=studio-use-image]').waitFor({timeout:30000});await page.locator('[data-action=studio-use-image]').click();await page.locator('#poster-canvas').waitFor();
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'studio-mobile.png')});await page.locator('[data-action=close]').click();
 await page.goto(url+'/#creative');await page.locator('.studio-jobs article').first().waitFor();assert.equal(await page.locator('.studio-jobs article').count(),2);await page.reload();await page.locator('.studio-jobs article').first().waitFor();assert.equal(await page.locator('.studio-jobs article').count(),2);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({ok:true,provider:'simulated',checks:['copy preview and selective apply','objectives persist in saved plan','poster templates','PNG download','image job and application','history after refresh','mobile layout'],errors}));
})().catch(async e=>{if(page)await page.screenshot({path:path.join(out,'studio-failure.png')});console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill();fs.closeSync(log)});
