'use strict';
const ORG={members:[],departments:[],invites:[],filter:{q:'',department:'all',role:'all',state:'all'},users:[],orgs:[],userFilter:{q:'',org:'',status:'all',page:1},selectedUser:null};
const orgButton=(label,a,id='',cls='')=>`<button type="button" class="btn ${cls}" data-org-action="${a}" data-id="${esc(id)}">${esc(label)}</button>`;
const badge=(text,kind='')=>`<span class="org-badge ${kind}">${esc(text)}</span>`;
function departmentOrder(rows=ORG.departments,parent=null,depth=0){return rows.filter(x=>x.parent_id===parent).flatMap(x=>[{...x,depth},...departmentOrder(rows,x.id,depth+1)])}
function departmentOptions(rows=ORG.departments){return [['','未分配部门'],...departmentOrder(rows).map(x=>[x.id,'　'.repeat(x.depth)+x.name])]}
function departmentPath(id,rows=ORG.departments){const parts=[],seen=new Set();while(id&&!seen.has(id)){seen.add(id);const d=rows.find(x=>x.id===id);if(!d)break;parts.unshift(d.name);id=d.parent_id}return parts.join(' / ')||'未分配部门'}
function descendants(id){const ids=new Set([id]);for(let i=0;i<ORG.departments.length;i++)for(const d of ORG.departments)if(ids.has(d.parent_id))ids.add(d.id);return ids}
function memberRoleOptions(){return Object.entries(roles).filter(([k])=>k!=='owner'||role()==='owner')}
async function peopleView(){
 [ORG.members,ORG.departments,ORG.invites]=await Promise.all([api('/orgs/'+S.org+'/members'),api('/orgs/'+S.org+'/departments'),api('/orgs/'+S.org+'/invites')]);
 if(ORG.filter.department!=='all'&&ORG.filter.department!==''&&!ORG.departments.some(d=>d.id===ORG.filter.department))ORG.filter.department='all';
 renderPeople();
}
function renderPeople(){
 const f=ORG.filter,selected=descendants(f.department),ms=ORG.members.filter(m=>(!f.q||(m.name+' '+m.email+' '+m.job_title).toLowerCase().includes(f.q.toLowerCase()))&&(f.department==='all'||(f.department===''?!m.department_id:selected.has(m.department_id)))&&(f.role==='all'||m.role===f.role)&&(f.state==='all'||(f.state==='active'?m.state==='active'&&m.account_active:m.state!=='active'||!m.account_active)));
 $('#content').innerHTML=head('机构成员','管理成员归属、岗位和权限。部门用于组织人员，角色决定操作范围。',orgButton('添加已注册用户','member-add','','primary')+orgButton('邀请成员','invite')+link('管理组织架构','departments'))+
 `<div class="org-metrics">${[['机构成员',ORG.members.length],['正常成员',ORG.members.filter(m=>m.state==='active'&&m.account_active).length],['部门',ORG.departments.length],['待接受邀请',ORG.invites.filter(i=>!i.used&&i.expires>Date.now()/1000).length]].map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('')}</div>
 <div class="org-directory"><aside class="department-sidebar"><h2>组织架构</h2><button class="department-node ${f.department==='all'?'selected':''}" data-org-action="department-filter" data-id="all">全部成员 <span>${ORG.members.length}</span></button><button class="department-node ${f.department===''?'selected':''}" data-org-action="department-filter" data-id="">未分配部门</button>${departmentOrder().map(d=>`<button class="department-node depth-${d.depth} ${f.department===d.id?'selected':''}" data-org-action="department-filter" data-id="${esc(d.id)}">${esc(d.name)}<span>${d.member_count}</span></button>`).join('')}<p class="hint">点击部门可查看本级及下级成员。</p></aside><section class="org-directory-main"><form id="orgx-member-filter" class="org-filter">${field('姓名 / 邮箱 / 岗位','q',f.q,'search','maxlength="100"')}${select('角色','role',[['all','全部角色'],...Object.entries(roles)],f.role)}${select('状态','state',[['all','全部状态'],['active','正常'],['disabled','已停用']],f.state)}<button class="btn" type="submit">查询</button></form><div class="table-wrap"><table class="directory-table"><thead><tr><th>成员</th><th>部门 / 岗位</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${ms.map(m=>`<tr><td><b>${esc(m.name)}</b><small>${esc(m.email)}</small></td><td>${esc(departmentPath(m.department_id))}<small>${esc(m.job_title||'未填写岗位')}</small></td><td>${badge(roles[m.role])}</td><td>${badge(!m.account_active?'账号停用':m.state==='active'?'正常':'机构内停用',m.account_active&&m.state==='active'?'good':'muted')}</td><td>${orgButton('编辑','member-edit',m.id,'small')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">没有符合条件的成员。</td></tr>'}</tbody></table></div><p class="hint">${ms.length} 位成员 · 停用仅影响当前机构；平台账号停用会影响全部机构。</p></section></div>
 <details class="panel org-invitations"><summary>邀请记录 · ${ORG.invites.length}</summary><div class="table-wrap"><table><thead><tr><th>邮箱</th><th>部门</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${ORG.invites.map(i=>`<tr><td>${esc(i.email)}</td><td>${esc(i.department_name||'未分配部门')}</td><td>${roles[i.role]}</td><td>${i.used===1?'已接受':i.used===2?'已撤销':i.expires<Date.now()/1000?'已过期':'待接受'}</td><td>${!i.used&&i.expires>Date.now()/1000?orgButton('撤销','invite-revoke',i.id,'small'):''}</td></tr>`).join('')||'<tr><td colspan="5">暂无邀请记录。</td></tr>'}</tbody></table></div></details>`;
}
function memberModal(id){const m=ORG.members.find(x=>x.id===id);modal(m?'编辑机构成员':'添加已注册用户',`<form id="orgx-member" class="form-grid" data-id="${esc(id||'')}">${m?`<p class="full"><b>${esc(m.name)}</b> · ${esc(m.email)}</p>`:field('已注册邮箱','email','','email','required')}${select('机构角色','role',memberRoleOptions(),m?.role||'learner')}${select('所属部门','department_id',departmentOptions(),m?.department_id||'')}${field('岗位 / 职务','job_title',m?.job_title||'','text','maxlength="100"')}${select('机构成员状态','state',[['active','正常'],['disabled','停用']],m?.state||'active')}<p class="hint full">普通成员可以学习、组课和询价；讲师、运营、管理员按角色获得机构后台权限。负责人只能由负责人调整。</p><div class="full"><button class="btn primary" type="submit">保存成员</button></div></form>`)}
function invitationModal(){modal('邀请加入机构',`<form id="orgx-invite" class="form-grid">${field('受邀邮箱','email','','email','required')}${select('机构角色','role',Object.entries(roles).filter(([k])=>k!=='owner'),'learner')}${select('所属部门','department_id',departmentOptions(),'')}${field('岗位 / 职务','job_title','','text','maxlength="100"')}<p class="hint full">邀请有效期为 7 天，需使用指定邮箱登录或注册后接受。同一邮箱再次邀请将撤销旧链接。</p><div class="full"><button class="btn primary" type="submit">生成邀请链接</button></div></form><div id="invite-result"></div>`)}
async function departmentsView(){ORG.departments=await api('/orgs/'+S.org+'/departments');$('#content').innerHTML=head('组织架构','按学院、校区、中心或部门建立层级，最多支持六级。',orgButton('创建部门','department-add','','primary')+link('返回机构成员','members'))+`<section class="panel"><div class="org-tree-heading"><b>${esc(S.orgs.find(o=>o.id===S.org)?.name||'当前机构')}</b><span>${ORG.departments.length} 个部门</span></div>${departmentOrder().map(d=>`<div class="department-row depth-${d.depth}"><div><span class="department-icon" aria-hidden="true">▣</span><b>${esc(d.name)}</b><small>${d.member_count} 位成员 · 排序 ${d.sort_order}</small></div><div class="actions">${orgButton('添加下级','department-child',d.id,'small')}${orgButton('编辑','department-edit',d.id,'small')}${orgButton('删除','department-delete',d.id,'small')}</div></div>`).join('')||'<div class="empty">尚未建立部门。可先创建一级部门，再添加下级部门。</div>'}<p class="hint">调整上级部门时，下级部门会一并移动。有成员、下级部门或待接受邀请的部门不能删除。</p></section>`}
function departmentModal(id,parent=null){const d=ORG.departments.find(x=>x.id===id),excluded=id?descendants(id):new Set();modal(d?'编辑部门':'创建部门',`<form id="orgx-department" class="form-grid" data-id="${esc(id||'')}">${field('部门名称','name',d?.name||'','text','required maxlength="80"')}${select('上级部门','parent_id',[['','机构直属部门'],...departmentOrder().filter(x=>!excluded.has(x.id)).map(x=>[x.id,'　'.repeat(x.depth)+x.name])],d?.parent_id||parent||'')}${field('显示顺序（数字越小越靠前）','sort_order',d?.sort_order||0,'number','min="0" max="9999" required')}<div class="full"><button class="btn primary" type="submit">保存部门</button></div></form>`)}
async function myOrganizationsView(){if(!requireLogin())return;const items=await api('/my/organizations');$('#content').innerHTML=head('我的机构','查看当前账号加入的机构、部门和角色。')+`<div class="org-cards">${items.map(x=>`<article class="panel"><div class="org-card-title"><h2>${esc(x.name)}</h2>${badge(!x.active?'机构停用':x.state==='active'?'正常':'成员停用',x.active&&x.state==='active'?'good':'')}</div><dl class="org-facts"><dt>所属部门</dt><dd>${esc(x.department_name||'未分配部门')}</dd><dt>岗位 / 职务</dt><dd>${esc(x.job_title||'未填写')}</dd><dt>机构角色</dt><dd>${esc(roles[x.role])}</dd></dl>${x.active&&x.state==='active'?orgButton('进入机构课程','switch-org',x.id):''}</article>`).join('')||'<section class="panel empty">你尚未加入机构。可使用机构管理员提供的邀请链接加入，或由管理员分配归属。</section>'}</div>`}
async function platformOrgsView(){ORG.orgs=await api('/platform/orgs');$('#content').innerHTML=head('机构管理','管理平台入驻机构、负责人和启停状态。机构业务权限由成员角色独立控制。',orgButton('创建机构','platform-org-add','','primary')+link('用户管理','platform-users'))+`<div class="org-metrics"><div><strong>${ORG.orgs.length}</strong><span>全部机构</span></div><div><strong>${ORG.orgs.filter(o=>o.active).length}</strong><span>正常机构</span></div></div><div class="org-cards">${ORG.orgs.map(o=>`<article class="panel"><div class="org-card-title"><h2>${esc(o.name)}</h2>${badge(o.active?'正常':'已停用',o.active?'good':'')}</div><p class="muted">${esc(o.description||'暂无机构介绍')}</p><dl class="org-facts"><dt>负责人</dt><dd>${o.owners.map(x=>esc(x.name)+' · '+esc(x.email)).join('<br>')||'暂无有效负责人'}</dd><dt>组织规模</dt><dd>${o.member_count} 位成员 / ${o.department_count} 个部门</dd></dl><div class="actions">${orgButton('编辑机构','platform-org-edit',o.id)}${orgButton('查看成员','platform-org-users',o.id)}</div></article>`).join('')||'<div class="empty">暂无机构，可创建第一个机构。</div>'}</div>`}
function platformOrgModal(id){const o=ORG.orgs.find(x=>x.id===id);modal(o?'编辑机构':'创建机构',`<form id="orgx-platform-org" data-id="${esc(id||'')}" class="form-grid">${field('机构名称','name',o?.name||'','text','required minlength="2" maxlength="100"')}${o?select('状态','active',[['1','正常'],['0','停用']],o.active?'1':'0'):field('负责人已注册邮箱','owner_email','','email','required')}${area('机构介绍','description',o?.description||'','maxlength="2000"')}<p class="hint full">${o?'停用后，机构公开课程和内部业务均不可访问，历史数据保留；成员仍可使用其他机构。':'负责人必须已有平台账号。可先在用户管理创建账号，再创建机构。'}</p><div class="full"><button class="btn primary" type="submit">保存机构</button></div></form>`)}
async function platformUsersView(){const f=ORG.userFilter;const [result,orgs]=await Promise.all([api('/platform/users?'+new URLSearchParams({...f,size:20})),api('/platform/orgs')]);ORG.orgs=orgs;ORG.users=result.items;$('#content').innerHTML=head('用户管理','管理平台账号与机构归属。同一个账号可以在不同机构拥有独立角色。',orgButton('创建用户','user-add','','primary')+link('机构管理','platform-orgs'))+`<form id="orgx-user-filter" class="org-filter panel">${field('姓名 / 邮箱','q',f.q,'search','maxlength="100"')}${select('机构归属','org',[['','全部机构'],['unassigned','未加入任何机构'],...orgs.map(o=>[o.id,o.name])],f.org)}${select('账号状态','status',[['all','全部状态'],['active','正常'],['disabled','已停用']],f.status)}<button class="btn" type="submit">查询</button></form><div class="panel table-wrap"><table class="directory-table"><thead><tr><th>用户</th><th>机构归属</th><th>账号状态</th><th>操作</th></tr></thead><tbody>${result.items.map(u=>`<tr><td><b>${esc(u.name)}</b>${u.platform_admin?badge('平台管理员'):''}<small>${esc(u.email)}</small></td><td>${u.memberships.map(m=>`<div class="membership-line">${esc(m.org_name)} · ${esc(roles[m.role])}<small>${esc(m.department_name||'未分配部门')}${!m.org_active?' · 机构停用':m.state!=='active'?' · 成员停用':''}</small></div>`).join('')||'<span class="muted">未加入机构</span>'}</td><td>${badge(u.active?'正常':'已停用',u.active?'good':'')}</td><td><div class="actions">${orgButton('编辑账号','user-edit',u.id,'small')}${orgButton('机构归属','user-memberships',u.id,'small')}</div></td></tr>`).join('')||'<tr><td colspan="4" class="empty">没有符合条件的用户。</td></tr>'}</tbody></table><div class="org-pagination"><span>共 ${result.total} 位用户 · 第 ${f.page} / ${Math.max(1,Math.ceil(result.total/20))} 页</span><div class="actions">${f.page>1?orgButton('上一页','users-page',f.page-1):''}${f.page*20<result.total?orgButton('下一页','users-page',f.page+1):''}</div></div></div>`}
function userModal(id){const u=ORG.users.find(x=>x.id===id);modal(u?'编辑用户账号':'创建用户账号',`<form id="orgx-user" data-id="${esc(id||'')}" class="form-grid">${field('姓名','name',u?.name||'','text','required maxlength="80"')}${u?`<p>邮箱：${esc(u.email)}</p>`:field('登录邮箱','email','','email','required')}${u?select('账号状态','active',[['1','正常'],['0','停用']],u.active?'1':'0'):''}<p class="hint full">${u?'停用账号会立即注销登录，并阻止访问所有机构。唯一有效负责人不能直接停用。':'系统生成随机初始密码，仅创建成功时展示。账号创建后可继续设置机构归属。'}</p><div class="full"><button class="btn primary" type="submit">${u?'保存账号':'创建账号'}</button></div></form>`)}
function userMembershipModal(id){const u=ORG.users.find(x=>x.id===id)||ORG.selectedUser;ORG.selectedUser=u;modal('机构归属 · '+u.name,`<div class="org-membership-list">${u.memberships.map(m=>`<article><div><b>${esc(m.org_name)}</b><p>${esc(roles[m.role])} · ${esc(m.department_name||'未分配部门')} · ${m.state==='active'?'正常':'停用'}</p></div>${orgButton('调整归属','membership-edit',m.org_id)}</article>`).join('')||'<p class="muted">尚未加入机构。</p>'}</div>${orgButton('加入机构','membership-add','','primary')}`)}
async function membershipForm(orgId=''){const u=ORG.selectedUser,m=u.memberships.find(x=>x.org_id===orgId);const available=ORG.orgs.filter(o=>o.active&&(m||!u.memberships.some(x=>x.org_id===o.id)));const id=orgId||available[0]?.id||'';const deps=id?await api('/platform/orgs/'+id+'/departments'):[];modal('设置机构归属 · '+u.name,`<form id="orgx-membership" data-user="${esc(u.id)}" class="form-grid">${select('机构','org_id',m?[[orgId,ORG.orgs.find(o=>o.id===orgId)?.name||m.org_name]]:available.map(o=>[o.id,o.name]),id,'required id="membership-org"')}${select('机构角色','role',Object.entries(roles),m?.role||'learner')}${select('所属部门','department_id',departmentOptions(deps),m?.department_id||'','id="membership-department"')}${field('岗位 / 职务','job_title',m?.job_title||'','text','maxlength="100"')}${select('成员状态','state',[['active','正常'],['disabled','停用']],m?.state||'active')}<p class="hint full">每个机构独立分配角色和部门。调动到另一机构时，先添加新归属，再按需要停用旧归属；历史记录保留。</p><div class="full"><button class="btn primary" type="submit" ${id?'':'disabled'}>保存归属</button></div>${!id?'<p class="hint full">没有可加入的正常机构，请先创建或启用机构。</p>':''}</form>`)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-org-action]');if(!b||b.disabled)return;const a=b.dataset.orgAction,id=b.dataset.id;try{
 if(a==='member-add')memberModal();if(a==='member-edit')memberModal(id);if(a==='invite')invitationModal();
 if(a==='department-filter'){ORG.filter.department=id;renderPeople()}
 if(a==='department-add')departmentModal();if(a==='department-child')departmentModal(null,id);if(a==='department-edit')departmentModal(id);
 if(a==='department-delete'&&confirm('确认删除此空部门？有成员或下级部门时不能删除。')){await api(`/orgs/${S.org}/departments/${id}`,'DELETE');await departmentsView();toast('部门已删除')}
 if(a==='invite-revoke'&&confirm('撤销后此邀请链接将无法使用。确认撤销？')){await api(`/orgs/${S.org}/invites/${id}`,'DELETE');await peopleView();toast('邀请已撤销')}
 if(a==='platform-org-add')platformOrgModal();if(a==='platform-org-edit')platformOrgModal(id);
 if(a==='platform-org-users'){ORG.userFilter={q:'',org:id,status:'all',page:1};location.hash='platform-users';await route()}
 if(a==='user-add')userModal();if(a==='user-edit')userModal(id);if(a==='user-memberships')userMembershipModal(id);
 if(a==='membership-edit')await membershipForm(id);if(a==='membership-add')await membershipForm();
 if(a==='users-page'){ORG.userFilter.page=+id;await platformUsersView()}
 if(a==='switch-org'){await loadOrg(id);$('#org-select').value=id;location.hash='catalog';await route()}
 }catch(err){error(err)}});
document.addEventListener('submit',async e=>{const f=e.target;if(!f.id.startsWith('orgx-'))return;e.preventDefault();const b=$('button[type=submit]',f);if(b?.disabled)return;if(b)b.disabled=true;const d=Object.fromEntries(new FormData(f));try{
 switch(f.id){
 case 'orgx-member-filter':ORG.filter={...ORG.filter,...d};renderPeople();break;
 case 'orgx-user-filter':ORG.userFilter={...d,page:1};await platformUsersView();break;
 case 'orgx-member':await api('/orgs/'+S.org+'/members'+(f.dataset.id?'/'+f.dataset.id:''),f.dataset.id?'PUT':'POST',{...d,department_id:d.department_id||null});$('#dialog').close();await refreshIdentity();await route();toast('成员已保存');break;
 case 'orgx-department':await api('/orgs/'+S.org+'/departments'+(f.dataset.id?'/'+f.dataset.id:''),f.dataset.id?'PUT':'POST',{...d,parent_id:d.parent_id||null,sort_order:+d.sort_order});$('#dialog').close();await departmentsView();toast('部门已保存');break;
 case 'orgx-invite':{const r=await api('/orgs/'+S.org+'/invites','POST',{...d,department_id:d.department_id||null});$('#invite-result').innerHTML=`<p class="hint">${esc(r.note)}</p><div class="linkbox"><a href="${esc(r.url)}">${esc(r.url)}</a></div>`;ORG.invites=await api('/orgs/'+S.org+'/invites');renderPeople();break}
 case 'orgx-platform-org':await api(f.dataset.id?'/platform/orgs/'+f.dataset.id:'/orgs',f.dataset.id?'PUT':'POST',f.dataset.id?{...d,active:d.active==='1'}:d);$('#dialog').close();await refreshIdentity();await refreshOrgs();await platformOrgsView();toast('机构已保存');break;
 case 'orgx-user':{const r=await api('/platform/users'+(f.dataset.id?'/'+f.dataset.id:''),f.dataset.id?'PUT':'POST',f.dataset.id?{name:d.name,active:d.active==='1'}:d);await refreshIdentity();await platformUsersView();if(r.initial_password){ORG.selectedUser={id:r.id,email:r.email,name:d.name,memberships:[]};modal('用户账号已创建',`<p>邮箱：<b>${esc(r.email)}</b></p><p>初始密码：</p><code class="initial-password">${esc(r.initial_password)}</code><p class="hint">${esc(r.note)}</p><div class="actions">${orgButton('设置机构归属','user-memberships',r.id,'primary')}</div>`)}else{$('#dialog').close();toast('账号已更新')}break}
 case 'orgx-membership':await api('/platform/users/'+f.dataset.user+'/memberships','PUT',{...d,department_id:d.department_id||null});$('#dialog').close();await refreshIdentity();await platformUsersView();toast('机构归属已更新');break;
 }
 }catch(err){error(err)}finally{if(b)b.disabled=false}});
document.addEventListener('change',async e=>{if(e.target.id!=='membership-org')return;try{const id=e.target.value,deps=await api('/platform/orgs/'+id+'/departments');if($('#membership-org')?.value===id)$('#membership-department').innerHTML=departmentOptions(deps).map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('')}catch(err){error(err)}});
